# Generated by Django 3.2.7 on 2021-12-06 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=20, verbose_name='По-батькові')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Електронна адреса')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.IntegerField(choices=[(0, 'secretary'), (1, 'admin'), (2, 'visitor'), (3, 'teacher')], default=0, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активний')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
