# Generated by Django 3.2.7 on 2021-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name="Ім'я")),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='Прізвище')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='По-батькові')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
    ]
