version: "3"

services:
  db:
      image: postgres
      expose:
        - "5433"
      ports:
        - "5433:5433"

  web:
      build: .
      depends_on:
        - db
      volumes:
        - .:/usr/src/app
      ports:
        - "5000:5000"
