# Generated by Django 3.2.7 on 2021-12-06 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('score_summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresummary',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='scoresummary',
            name='subject',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='score_summary.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ManyToManyField(to='score_summary.Subject'),
        ),
    ]
