# Generated by Django 3.2.7 on 2021-09-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score_summary', '0002_scoresummary_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresummary',
            name='subject',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='score_summary.subject', verbose_name='Предмет'),
        ),
    ]
