# Generated by Django 3.2.7 on 2022-01-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score_summary', '0003_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='value',
            field=models.CharField(blank=True, choices=[('', ''), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('зарах.', 'зарах.')], max_length=10, null=True, verbose_name='Оцінка'),
        ),
        migrations.AlterField(
            model_name='scoresummary',
            name='point',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='score_summary.point', verbose_name='Оцінка'),
        ),
    ]
