# Generated by Django 3.2.7 on 2022-01-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score_summary', '0005_auto_20220117_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresummary',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='score_summary.point', verbose_name='Оцінка'),
        ),
    ]
