# Generated by Django 3.2.7 on 2021-09-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('point', '0001_initial'),
        ('group', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name="Ім'я")),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='Прізвище')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='По-батькові')),
                ('group', models.OneToOneField(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Група')),
                ('points', models.ForeignKey(blank=True, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='point.point')),
                ('subjects', models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
    ]
