# Generated by Django 3.2.7 on 2021-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_summary', '0003_scoresummary_subject'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, max_length=20, to='score_summary.Group', verbose_name='Група'),
        ),
    ]
