# Generated by Django 3.2.7 on 2021-10-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score_summary', '0003_scoresummary_subject'),
        ('student', '0002_auto_20211013_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='score_summary.group', verbose_name='Група'),
            preserve_default=False,
        ),
    ]
