name: Testing
on: push

jobs:
  scoresummary:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |
          cd statement
          pip3 install -r requirements.txt --user Django
          python3 manage.py test
