name: Testing
on: push

jobs:
  scoresummary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |
          cd statement
          sudo apt-get install python3-setuptools
          pip3 install setuptools-rust
          pip3 install -r requirements.txt
          python3 manage.py test
