name: Testing
on: push

jobs:
  scoresummary:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |
          cd statement
          sudo apt-get install python3-setuptools
          pip3 install setuptools-rust
          pip3 install -r requirements.txt
          python3 manage.py test
