name: Testing
on: push

jobs:
  scoresummary:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |
          pip3 install --user django
          cd statement
          python3 manage.py test
